### ISSUE TITLE
C++11 support

### ISSUE THREAD

**Issue by StefanoSperetta** [FlaReSS/gr-ecss#13]
When building for GNU Radio 3.8, C++11 must be setas standard but this proves problematic under macOS.

I tried to follow online troubleshooting guides but it keeps failing to build properly. Maybe C++11 should be set by default in the CMAKE build script such that it is not needed to add it on command line?

**Comment by StefanoSperetta** [comment]
Adding set(CMAKE_CXX_STANDARD 11) to gr-ecss->CMakeLists.txt (at the beginning) fixes the issue but I am not sure this is the proper way to handle this. @noc0lour any idea?

**Comment by noc0lour** [comment]
I think this is how to do it, I guess my compilers all default to some higher standard anyway and thus I did not find this issue.

**Comment by StefanoSperetta** [comment]
Fixed in ee28d3255864dca684da2a24b888778d2e95b7f9, also merged into main.
